config/routes.rb
Rails.application.routes.draw do

  match '/logout', to: 'sessions#destroy', via: [:get, :post]
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  resources :users, path: 'u' do
    get :curl, on: :member
    get :demo, on: :collection
    get :demo_curl, on: :collection

    resources :charges, except:[:index, :show] do
      post :plan, :on => :collection
      post :unsubscribe, :on => :collection
    end

    get :tor, on: :member
    get :blacklist, on: :member
    post :post_update, on: :member
  end

  # API
  namespace :v1, defaults: {format: :json} do
    get :api, to: 'users#api', :path => '/'
  end

  # match '/:locale' => 'evangelists#index', via: [:get], :as => 'locale_root'
   root 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_token

  has_many :identities, dependent: :destroy

  has_many :userips, dependent: :destroy
  has_many :ips, through: :userips, source: :ip

  has_many :onlineforms, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable,
    :lockable, :omniauthable, :omniauth_providers => [:facebook, :twitter, :google, :stripe_connect]

  # user name should be unique
  validates :user_name, presence: true, uniqueness: true

  # upload user icon to s3
  has_attached_file :image_user, styles:
  {
    medium: {geometry: "64x64>", format: 'png'},
    thumb: {geometry: "32x32>", format: 'png'},
  },
  preserve_files: false,
  :storage => :s3,
  :path => ":attachment/:id/:style/:filename",
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :url => ':s3_alias_url',
    :s3_alias_url => "i.torblocker.com",
    :s3_host_alias => 'i.torblocker.com',
    :s3_protocol => :https

  validates_attachment_content_type :image_user,
    content_type: /\Aimage\/.*\Z/,
    message: 'only jpeg, gif, png'

  validates_attachment_size :image_user,
    less_than: 1.megabyte,
    message: 'Check if the image is less than 1MB'

  def self.find_for_oauth(auth, this_user)
    # Find an identity here
    @identity = Identity.find_with_omniauth(auth)
    # If no identity was found, create a brand new one here
    if @identity.nil?
      @identity = Identity.create_with_omniauth(auth)
    end

    if this_user != nil
      if @identity.user == this_user
        # Identity is already associated with this user
      else
        # Identity is not associated with the current_user
        @identity.user = this_user
        @identity.save
      end
      user = this_user
    else
      if @identity.user.present?
        # Identity has a user associated with it
        user = @identity.user
      else
        # No user associated with the identity so we need to create a new one
        user = User.where(user_name: auth.info.name).first
        if user == nil
          user = User.create(
            user_name: auth.info.name,
            email:    User.get_email(auth),
            password: Devise.friendly_token[6, 30],
            image_user: auth.info.image
          )
        else
          user = User.create(
          user_name: auth.info.name + "_" + [*('a'..'z'),*('0'..'9')].shuffle[0,3].join,
          email: User.get_email(auth),
          password: Devise.friendly_token[6, 30],
          image_user: auth.info.image
          )

        end
        @identity.user = user
        @identity.save
      end
    end
    user
  end

  private
  def set_token
    return if auth_token.present? # guard clause
    self.auth_token = generate_token
  end

  def generate_token
    loop do
      token = SecureRandom.hex
      break token unless self.class.exists?(auth_token: token)
    end
  end

  def self.get_email(auth)
    email = auth.info.email
    email = "#{auth.provider}-#{auth.uid}@example.com" if email.blank?
    email
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
skip_before_filter :require_no_authentication                            
  def create                                        

    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        # sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    auth = request.env['omniauth.auth']
    origin = request.env['omniauth.origin']
    destination = origin.blank? ? root_path : origin
  # Find an identity here
  @identity = Identity.find_with_omniauth(auth)

  if @identity.nil?
    # If no identity was found, create a brand new one here
    @identity = Identity.create_with_omniauth(auth)
  end

  if signed_in?
    if @identity.user == current_user
      # Identity is already associated with this user
      redirect_to @user, notice: "Already logged in and linked!"
    else
      # Identity is not associated with the current_user
      @identity.user = current_user
      @identity.save
      redirect_to @user, notice: "Account was successfully linked!"
    end
  else
    if @identity.user.present?
       # Identity has a user associated with it
      self.current_user = @identity.user
      redirect_to root_url, notice: "Signed in!"
    else
      # No user associated with the identity so we need to create a new one
      user = User.create_with_omniauth(auth['info'])
      @identity.user = user
      @identity.save()
      self.current_user = @identity.user
      redirect_to new_user_url, notice: "Registration successful"
    end
  end
  end

  # DELETE /resource/sign_out
  def destroy
    super
    self.current_user = nil
    # redirect_to root_url, notice: "Signed out successfully"
  end

  def omniauth_failure
    origin = request.env['omniauth.origin']
    destination = origin.blank? ? root_path : origin
    redirect_to destination, alert: "Connection failed"
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :login
  before_action :set_user, only: [:show, :curl, :edit, :update, :destroy, :post_update, :tor, :blacklist]
  skip_before_filter :require_no_authentication, :only => [:new, :create]

  def index
    @head_type = 0
    @ruby_or_curl = 0
  end

  def show
    @ruby_or_curl = 0
    @auth_token = @user.auth_token
  end

  def curl
    @ruby_or_curl = 1
    @auth_token = @user.auth_token
    render 'show'
  end

  def demo
    # demo user will be of id: 2
    # don't forget doing $rake db:seed
    @user = User.find_by(id: 2)
    @ruby_or_curl = 0
    @demo = 1
    # auth_token for demo user
    @auth_token = "sign_in_to_get_your_token"
    render 'show'
  end

  def demo_curl
    @user = User.find_by(id: 2)
    @demo = 1
    @ruby_or_curl = 1
    @auth_token = "sign_in_to_get_your_token"
    render 'show'
  end

  def api
    if params[:ip] != nil
      if @user.ips.exists?(a: params[:ip])
        @y = 1
      else
        @y = 0
      end
    end

    respond_to do |f|
      f.html { @user }
      f.json { render json: @y, status: 200 }
    end
  end

  def tor
    if params[:b] == "0" # set blocking OFF
      @user.tor = 0
      @user.save!

      Userip.joins(:ip).joins(:user).where(
        'ips.p' => 0,'users.id' => @user.id
      ).delete_all
      flash[:notice] = "Tor browser - UNBLOCKING"

    elsif params[:b] == "1" # set blocking ON
      @user.tor = 1
      @user.save!

      inserts = []
      Ip.where(p: 0).each{|ip| inserts.push "(#{@user.id}, #{ip.id})"}
      sql = 'INSERT INTO userips ("user_id", "ip_id") VALUES' + inserts.join(", ").to_s
      ActiveRecord::Base.connection.execute sql
      flash[:notice] = "Tor browser - BLOCKING"

    end

    render 'pref.js'

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # if @user.save
    #   Mailer.sendmail_confirm(@user).deliver
    # end

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Welcome!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user == current_user
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User settings are updated' }
          format.json { render :show, status: :ok, location: @user }
          format.js
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      reset_session
      user = User.find(@user_id)
      user.destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'Your accout was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def current_user_home
    if user_signed_in?
      redirect_to current_user
    else
      redirect_to users_path
    end
  end

  private
  def login
    if session[:user_id].blank?
      user = User.create
      session[:user_id] = user.id
    end
    @user_id = session[:user_id]
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:ip, :b, :user_name, :password, :email, :image_user)
  end
end

app/controllers/v1/users_controller.rb
module V1
  class UsersController < ApplicationController
    protect_from_forgery with: :null_session

    def api
      # input:
      # ip (string): IP address

      # output:
      # return 0 if IP address is not on the torblocker list
      # return 1 if IP address is on the torblocker list

      authenticate

      @y = 0 # output

      if params[:ip] != nil
        ip = Ip.find_by(a: params[:ip])
        if @user.ips.exists?(a: params[:ip])
          @y = 1
          # this ip should be blocked. write a log to user.history
          if @user.history.size > 50
            @user.history.shift
            @user.history << [ip.id, 0.day.ago]
          else
            @user.history << [ip.id, 0.day.ago]
          end
          @user.save!
        end
      end

      respond_to do |f|
        f.json { render json: @y, status: 200 }
      end
    end

    private
    def user_params
      params.require(:user).permit(:ip)
    end

    protected
    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      authenticate_with_http_token do |token, options|
        @user = User.find_by(auth_token: token)
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm="Users"'

      respond_to do |format|
        format.json { render json: 'Bad credentials', status: 401 }
      end
    end
  end
end

app/views/users/_alert.html.erb
  <% flash.each do |name, value| %>
      <div class="alert alert-<%= name %> custom-alert">
          <div align="center"><%= value %></div>
      </div>
  <%end%>

app/views/users/_all_likes.html.erb
<% if @user != nil %>
<% @liked_evangelists.each do |evangelist| %>
          <div class="media">
            <div class="media-left" style="width:4em; overflow:hidden;">
<li class="like_list_e like_list_e_i">
  <div class="likes_e_i_div" align="center">
  <%= evangelist.likes_e %>
  </div>
    <h4 style="display:inline; line-height:1.3em">
      <% if user_signed_in? %>
              <% if current_like_of(evangelist) %>
                <%= link_to ('<i class="fa fa-heart" aria-hidden="true" style="color:#FF006E; font-size:1.3em;"></i>').html_safe, evangelist_like_path(evangelist, current_like_of(evangelist),formating: 'user'), :method => :delete, :remote => true, :format => :js%>
              <% else %>
                <%= link_to ('<i class="fa fa-heart-o" aria-hidden="true" style="color:#FF006E;font-size:1.3em;"></i>').html_safe, evangelist_likes_path(evangelist, formating: 'user'), :method => :post, :remote => true, :format => :js%>
              <% end %>
      <% else %>
            <a id="loginfirst" role="button"><i class="fa fa-heart-o" aria-hidden="true" style="color:#FF006E;font-size:1.3em;"></i></a>
      <% end %>
  </h4>
</li>
</div>
            
            <div class="media-left">
              <div class="image_i_div">
              <%= link_to evangelist do %>
                <%= image_tag evangelist.yt_img0, class: "article-index"%>
              <% end %>
              </div>
              
            </div>
            <div class="media-body" align="left">

              <%if evangelist.title_s != nil%>
                <div class ="title_i">
                  <%= link_to evangelist.title_s, evangelist, class: "link"%>
                </div>
              <%else%>
                <div class ="title_i">
                  <%= link_to evangelist.title, evangelist, class: "link"%>
                </div>
              <%end%>

              <div class="name_i">
                <%= time_ago_in_words(evangelist.created_at) %> ago by <%= link_to evangelist.user_name, evangelist.user, class: "link"%>
              </div>
              <div style="height:5px;"></div>
  <div class="tag_i_group_all">
  <% evangelist.categories.pluck(:name).each do |t| %>
    <div class="btn-group tag_i_group" role="group" area-label="Subscribe or Go to Categories">

    <% if user_categorize?(t) %>
      <%= button_to cate_path(cate_id(t)), method: :delete, class: 'btn btn-primary btn-xs', remote: true, params: {cate: t, eva_id: evangelist.id,formating: 'user'} do%>
        <i class="fa fa-heart" aria-hidden="true" style="color:#FF006E; font-size:1.0em;"></i>
      <% end %>
    <% else %>
      <%= button_to cate_index_path, class: 'btn btn-primary btn-xs', remote: true, params: {cate: t, eva_id: evangelist.id,formating: 'user'} do%>
        <i class="fa fa-heart" aria-hidden="true" style="color:#FFFFFF; font-size:1.0em;"></i>
      <% end %>
    <% end %>

      <button type="button" class="btn btn-primary btn-xs" style="background: linear-gradient(to bottom, #F7FAFF 0%,#fff 40% , #fff 60% ,#FFFBFF 100%);"><%= link_to t, category_path(t) %></button>

      <!-- <button type="button" class="btn btn-primary btn-xs" style="cursor: default;"><%= i_subscriber(t) %></button> -->
    </div>
  <%end%><!-- end of eva.cate -->
</div>

  </div>
</div>

<% end %><!-- end of @evangelists.each -->

<%end%>

app/views/users/_form.html.erb
<% if @user.id == current_user.id %>

<div style="width:700px;margin:0 auto;">
  <h2 align="center">Editing...</h2>
<%= form_for @user, :html => {:multipart => true} do |f| %>

  <div class="row">
  <div class="col-md-12"> <!-- user start -->
    <div align="center">User Name</div>
      <div class="user_name">
        <%= f.text_field :user_name, autocomplete: "off", required: false, class: "form-control" , style: "width:100%", value: @user.user_name%>
        <div id="form_image">
        <%= render 'form_image' %>
        </div>
      <div id="image_user_update">
         <%= f.file_field :image_user, :title => "Upload" %>
      </div>

      </div>

      <div align="center" style="padding-top:14px;">Bio</div>
      <div class="bio" style='font-weight:300;'>
        <% if @user.bio == "" %><% @user.bio = "Is " + @user.user_name + " is ninja? " + @user.user_name + "\'s bio is currently blank." %><%end%>
        <%= f.text_field :bio, autocomplete: "off", required: false, class: "form-control" , style: "width:100%", value: @user.bio%>
      </div>
  </div> <!-- user end -->
</div>
<br><br>

    <h4 align="center">Email (will not be public)</h4>
    <%= f.text_field :email, autocomplete: "on", required: false, class: "form-control" , style: "width:100%", value: @user.email%>
    <br><br><br>

  <div align="center">
    <%= f.submit "Done" , class: "btn btn-default", style: "width:10%"%>
  </div>

<% end %>
</div>

<% end %>

app/views/users/_form_image.html.erb
<%= image_tag @user.image_user.url(:medium), class: "profile_image" %>

app/views/users/_input_box.html.erb
<% if current_user.states == "curious for similar word" %>
	<%= form_for [@user, @mikutalk], remote: true, :url => similar_user_mikutalk_path(@user, @mikutalk) do |f| %>
		<%= f.text_field :question, id: "input_box_text", class: "text_i", placeholder: "Tell a similar word!" %>
	<%end%>
<%elsif current_user.states == "one_of"%>
	<%= form_for [@user, @mikutalk], remote: true, :url => oneof_user_mikutalk_path(@user, @mikutalk) do |f| %>
		<%= f.text_field :question, id: "input_box_text", class: "text_i", placeholder: "Tell an abstraction!" %>
    <%end%>
<%else%>
	<%= form_for [@user, @user.mikutalks.build], remote: true do |f| %>
		<div id="send_left">
	    		<%= f.text_field :question, id: "input_box_text", class: "text_i", placeholder: "Talk to Alice" %>
	    </div>
	<%end%>
<%end%>

app/views/users/_output_box.html.erb
<div id="output_box" align="left">
	<ul id="output_list">
		<% if @user.id == 2 %>
			Alice> Welcome to Alice's secret house. Just come in and talk to me!<br>
		<%else%>
		Alice> <% if user_signed_in? %>
			Howdy, <%= current_user.user_name%>?
			<%else%>
			Howdy?
			<%end%><br>
		<%end%>
	</ul>
</div>

app/views/users/new.html.erb
<div align="center" style="height:120px"></div>
<div class="row"><div class="col-md-6">

<h2>Signing in</h2>
	<br>
		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  		<%= devise_error_messages! %>
	  	<div class="form-inputs">
			<div>
		  		<%= f.text_field :user_name, required: true, autofocus: true, class: 'text_i_b', placeholder: " Name"%>
	  		</div>
	  		<br>
	  		<div>
		    	<%= f.email_field :email, required: true, class: 'text_i_b', placeholder: " e-mail"%>
			</div>
			<br>
			<div>
		    	<%= f.password_field :password, autocomplete: "off", required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) , class: 'text_i_b', placeholder: " Password"%>
			</div>
			<br>
			<div>
		    	<%= f.password_field :password_confirmation, autocomplete: "off", required: true , class: 'text_i_b', placeholder: " Password Confirmation"%>
	  		</div>
	  		<br>
			<div>
			　<%= f.check_box :agreement %>　 I read and accept <%= link_to "Terms", terms_path, class: "link"%>
	  		</div>
	  		<br>
	  		<div class="g-recaptcha" data-sitekey="6LcPBhgTAAAAAG0ify2nXoWV6gl472x95q3Opvq7"></div>
	  	</div>

	  	<div class="form-actions">
	    	<%= f.submit "Sign up" , class: 'button_b_up'%>
	  	</div>
	<% end %>
	<br/>
	<div align="right">
		<%= link_to '... forget password?', new_user_password_path , class: 'link_b'%>
	</div>


</div></div>

app/views/users/show.html.erb
<div class="ue_42">
<%= render 'alert' %>
</div>

<div class="container" style="margin-top:42px;">
  <div class="row">
    <div class="col-md-12"> <!-- user start -->
      <div class="bio_e_r">
        <% if @user != nil && @user == current_user%>
          <%= button_to 'Edit your profile', edit_user_path(@user.id), method: :get, class: "btn btn-default btn-sm", style: "display: inline-block;"%>
        <%else%>
        <%end%>
      </div>
      <div align="center" style="font-weight: 900; font-size: 12px; margin-top: 2px;">
        <%= link_to @user.user_name, @user, class: "link" %>
      </div>
    </div> <!-- user end -->
  </div>
<% if @user != nil %>
  <% if @user == current_user || @demo == 1 %>
    <div class="row">
      <div class="col-md-6">
        <h4 align="center">Preferences</h4>
        <script type="text/javascript">
          $(function(){
            <% if @user.tor == 0 %> document.getElementById("ckbox1").checked = true <%end%>
            $("#ckbox1").on('click', function () {
              if (document.getElementById("ckbox1").checked) //false means blocked
                {
                  $.get('/u/<%=@user.id%>/tor?b=0')
                  console.log("unblocked");
                }
              else if (!document.getElementById("ckbox1").checked)
                {
                  $.get('/u/<%=@user.id%>/tor?b=1')
                  console.log("blocked");
                }
            });
            <% if @user.blacklist == 0 %> document.getElementById("ckbox2").checked = true <%end%>
            $("#ckbox2").on('click', function () {
              if (document.getElementById("ckbox2").checked) //false means blocked
                {
                  $.get('/u/<%=@user.id%>/blacklist?b=0')
                  console.log("unblocked");
                }
              else if (!document.getElementById("ckbox2").checked)
                {
                  $.get('/u/<%=@user.id%>/blacklist?b=1')
                  console.log("blocked");
                }
            });
          });
        </script>
        <div class="make-switch">
          <div style="position:absolute;padding-left:10px;font-size:18px;line-height: 32px;">Tor browser</div>
          <div align="right" style="padding-right:10px;">
          <label class="switch">
            <input type="checkbox" id="ckbox1">
            <div class="slider round"></div>
          </label>
        </div>
      </div>

      <h4 align="center" style="padding-top:20px;">API Reference</h4>
      <%if @ruby_or_curl == 0 %> <!--   -->
        <span style="font-weight:900;">
        <span style="color: #ff2d00;">Ruby</span>
          <%if @demo == 1%>
            <%= link_to "curl", demo_curl_users_path, class: "link_rv", style:"margin-left:1em;"  %>
          <%else%>
            <%= link_to 'curl',curl_user_path(@user), class: "link_rv", style:"margin-left:1em;" %>
          <%end%>
        </span>

<pre><code>
# in your console
$ gem insall torblocker

# in your .rb file or .html.erb file
ip = request.remote_ip
token = "<%=@auth_token%>"

Torblocker.trusted?(ip, token)
# This returns true if the IP is not from Tor browser.

Torblocker.untrusted?(ip, token)
# This returns true if the IP is from Tor browser.
</code></pre>

  <% elsif @ruby_or_curl == 1 %><!--   -->
    <span style="font-weight:900;">
      <% if @demo == 1 %>
        <%= link_to "Ruby", demo_users_path, class: "link_rv", style:"margin-right:1em;" %>
      <% else %>
        <%= link_to 'Ruby',user_path(@user), class: "link_rv", style:"margin-right:1em;" %>
      <% end %>
      <span style="color:#ff2d00;">curl</span>
    </span>

<pre><code>
# in your console
$ curl https://torblocker.com/v1?ip=ip_to_be_checked -H "Authorization:Token token=<%=@auth_token%>"

# This returns 1 if ip_to_be_checked is from Tor browser or our blacklist, and 0 otherwise

# change ip_to_be_checked to a client IP
# e.g.) https://torblocker.com/v1?ip=255.255.0.1
</code></pre>

          <% end %><!--   -->
        </div>

        <div class="col-md-6">
          <h4 align="center">Logs</h4>
          <div class="bg_gray_2">
            <% @user.history.reverse.each do |x|%>
              <% i = Ip.find_by(id: x[0])%>
              <% if i != nil %>
                <%= i.a %> was blocked (
                <% if i.p[0] == 0 %>Tor<% else %>Others<% end %>)
                <% if x[1] != nil %>
                  , <%= time_ago_in_words(Time.at(x[1])).gsub(/about/,"").gsub(/less than/,"") %> ago
                <% end %>
              <% end %>
              <br>
            <% end %>
          </div>
        </div>

      </div>
    <% end %>
  <% end %>

</div>